name: Jekyll site CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    # https://github.com/actions/runner-images
    runs-on: ubuntu-22.04

    env:
      GITHUB_DEST_REPO: "xpack/dev-tools-web-preview"
      GIT_COMMIT_USER_EMAIL: "ilg@livius.net"
      GIT_COMMIT_USER_NAME: "Jekyll site CI"
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        # Version range or exact version of a Ruby version to use, using semver version range syntax.
        # https://www.ruby-lang.org/en/downloads/releases/
        # https://rubygems.org/gems/bundler
        ruby-version: '3.2'
    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libxslt-dev pkg-config
        gem install bundler:2.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        ls -l vendor/bundle
        bundle exec htmlproofer --version
    - name: Show environment
      run: |
        pwd
        env | sort
    - name: Run script to build site
      env:
        GITHUB_TOKEN: ${{ secrets.ILG_TOKEN }}
      run: bash scripts/ga-jekyll.sh
